### ISSUE TITLE
Consider adding BIOS to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [ideal-world/bios#14]
Hi @gudaoxuri, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by gudaoxuri** [comment]
Sea-orm is great project . I am very honored by your invitation, this project and related project( https://github.com/ideal-world/tardis ) are still in the incubation stage, so I will add them when they are mature, thanks again.

**Comment by billy1624** [comment]
Thanks! @gudaoxuri
